exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal -r
exec-once = hypridle
exec-once = hyprpaper
exec-once = blueman-applet
exec-once = waybar
exec-once = mullvad-vpn
exec-once = flatpak run com.bitwarden.desktop
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = $terminal
exec-once = emacs
exec-once = gtk-launch "Steam (No VPN)"
exec-once = hiddify
exec-once = kanshi
exec-once = syncthing
