windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = match:class firefox, workspace 2
windowrule = match:class zen, workspace 2
windowrule = match:class brave-bin, workspace 2
windowrule = match:class helium, workspace 2

windowrule {
    name = pip
    match:title = Picture-in-picture
    float = yes
    size = 495 287
    move = 1383 864
    pin = yes
    opaque = true
    no_initial_focus = true
    border_size = 2
}

windowrule {
    name = pipc
    match:title = Picture in picture
    float = yes
    size = 495 287
    move = 1412 777
    pin = yes
    opaque = true
    no_initial_focus = true
    border_size = 2
}

windowrule {
    name = ghostty
    match:class = com.mitchellh.ghostty
    opacity = .95
    workspace = 1
}

windowrule {
    name = steam
    match:class = steam
    workspace = 3 silent
}

windowrule {
    name = friendslist
    match:title = Friends List
    workspace = 3 silent
    size = 435 1089
}

windowrule {
    name = heroic
    match:class = heroic
    workspace = 3 silent
    float = yes
}

windowrule {
    name = discord
    match:class = discord
    workspace = 3 silent
    float = yes
}

windowrule = match:class org.prismlauncher.PrismLauncher, workspace 3

windowrule {
    name = vpn
    match:class = Mullvad VPN
    workspace = 4
    float = yes
    move = 1444 60
}

windowrule {
    name = passwd
    match:class = Bitwarden
    workspace = 4
    float = yes
    size = 651, 601
    move = 897, 74
}

windowrule {
    name = spotify
    match:class = spotify
    workspace = 3
    float = yes
    size = 859 960
    move = 15 130
}

windowrule {
    name = bluetooth
    match:class = blueman-manager
    float = yes
    size = 651 452
}

