#!/bin/sh
exec 2>&1
exec /home/dallas/opt/data/llama.cpp/build/bin/llama-server \
  --host 0.0.0.0 \
  --port 42069 \
  --models-dir /home/dallas/models \
  -t 10 \
  -ngl 99 \
  --ctx-size 64000 \
  --parallel 4
