;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-indent-line-or-region
        ignore
        meow-insert
        meow-insert-exit
        meow-next
        meow-prev
        my/cancel
        my/mc-add-cursor-below
        my/mc-delete-cursor
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        ))
