;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ignore
        meow-insert
        meow-insert-exit
        meow-left
        meow-next
        meow-next-symbol
        meow-prev
        meow-reverse
        meow-right
        meow-undo
        my/cancel
        my/mc-add-cursor-below
        my/mc-delete-cursor
        my/meow-delete-or-kill
        org-delete-char
        org-self-insert-command
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        meow-append
        ))
