#+TITLE: Dallas' Emacs Config
#+AUTHOR: A. Dallas Sherman
#+DESCRIPTION: Dallas' personal Emacs config
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of Contents :toc:
- [[#generally-important-things][Generally Important Things]]
  - [[#load-scripts][Load Scripts]]
  - [[#evil-mode][Evil Mode]]
- [[#general-keybindings][General Keybindings]]
- [[#nerd-icons][Nerd Icons]]
- [[#auto-trash-backups][Auto-Trash Backups]]
- [[#diminish][Diminish]]
- [[#dired][Dired]]
- [[#flycheck-and-flymake][Flycheck and Flymake]]
- [[#fonts][Fonts]]
- [[#important-settings][Important Settings]]
  - [[#disable-menubar-toolbars-and-scrollbars][Disable Menubar, toolbars and scrollbars]]
  - [[#line-numbers-and-truncated-lines][Line Numbers and Truncated Lines]]
  - [[#disable-startup-screen][Disable startup screen]]
  - [[#sensible-defaults][Sensible defaults]]
- [[#ivy-counsel][Ivy (Counsel)]]
- [[#company][Company]]
- [[#languages][Languages]]
  - [[#lsp][LSP]]
  - [[#apheleia-formatting][Apheleia (FORMATTING)]]
- [[#minibuffer-escape][Minibuffer escape]]
- [[#modeline][Modeline]]
- [[#org-mode][Org Mode]]
  - [[#enabling-table-of-contents][Enabling Table of Contents]]
  - [[#enabling-org-bullets][Enabling Org Bullets]]
  - [[#source-code-extension][Source Code Extension]]
- [[#projectile][Projectile]]
- [[#rainbow-mode][Rainbow Mode]]
- [[#reload-emacs][Reload Emacs]]
- [[#shells-and-terms][Shells and Terms]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm-Toggle]]
- [[#sudo-edit][Sudo Edit]]
- [[#theme][Theme]]
  - [[#themes-packages][Themes packages]]
  - [[#transparency][Transparency]]
- [[#which-key][Which-Key]]

* Generally Important Things 
** Load Scripts
*** Script Dir 
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src
*** Start scripts
#+begin_src emacs-lisp
(require 'elpaca-setup)  ;; The Elpaca Package Manager
(require 'buffer-move)   ;; Buffer-move for better window management
#+end_src

** Evil Mode
#+begin_src emacs-lisp
(use-package evil
  :ensure t
  :demand t
  :after elpaca
  :diminish
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (evil-mode))
(use-package evil-collection
  :after evil
  :diminish
  :ensure t
  :config
  (setq evil-collection-mode-list '(dashboard dired ibuffer))
  (evil-collection-init))
(use-package evil-tutor :ensure t :diminish)
(use-package evil-escape
  :ensure t
  :diminish
  :after evil
  :config
  (evil-escape-mode)
  (setq evil-escape-key-sequence "jk")
  (setq evil-escape-delay 0.2))
(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))

;; Using RETURN to follow links in Org/Evil 
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))
;; Setting RETURN key in org-mode to follow links
(setq org-return-follows-link  t)
#+end_src


* General Keybindings
#+begin_src emacs-lisp
(use-package general
  :ensure t
  :config
  (general-evil-setup)

  ;; set up 'SPC' as the global leader key
  (general-create-definer emacaroni/leader-key
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader
    :global-prefix "M-SPC") ;; access leader in insert mode
  
  ;; general
  (emacaroni/leader-key
    "SPC" '(find-file :wk "Find File")
    "/" '(counsel-M-x :wk "Counsel M-x")
    "co" '((lambda () (interactive) (find-file "~/.config/emacs/config.org")) :wk "Edit emacs config")
    "cr" '(reload-init-file :wk "Reload config")
    "fr" '(counsel-recentf :wk "Find recent files")
    "-" '(dired :wk "File Explorer (Dired)")
    "." '(counsel-fzf :wk "Fuzzy finder"))

   ;; org
   (emacaroni/leader-key
    "o" '(:ignore t :wk "Org")
    "o a" '(org-agenda :wk "Org agenda")
    "o e" '(org-export-dispatch :wk "Org export dispatch")
    "o i" '(org-toggle-item :wk "Org toggle item")
    "o t" '(org-todo :wk "Org todo")
    "o B" '(org-babel-tangel :wk "Org babel tangle")
    "o T" '(org-todo-list :wk "Org todo list")
    "o b" '(org-table-insert-hline :wk "Insert hline in table")
    "o d" '(org-time-stamp :wk "Org time stamp"))
    ;; buffer
    (emacaroni/leader-key
     "b" '(:ignore t :wk "Buffer")
     "bb" '(switch-to-buffer :wk "Switch buffer")
     "bk" '(kill-this-buffer :wk "Close current buffer")
     "bn" '(next-buffer :wk "Next buffer")
     "bp" '(previous-buffer :wk "Previous buffer")
     "bi" '(ibuffer :wk "IBuffer")
     "bd" '(evil-window-delete :wk "Close window")
     "bw" '(evil-window-new :wk "New window"))
    ;; splits
    (emacaroni/leader-key
      "s" '(:ignore t :wk "Split")
      "sh" '(evil-window-split :wk "New horizontal split")
      "sv" '(evil-window-vsplit :wk "New vertical split"))
    ;; dired
    (emacaroni/leader-key
     "d" '(:ignore t :wk "Dired")
     "dl" '(dired :wk "Open dired")
     "dj" '(dired-jump :wk "Dired jump to current")
     "dn" '(neotree-dir :wk "Open directory in neotree")
     "dp" '(peep-dired :wk "Peep-dired"))
    ;; evaluation
    (emacaroni/leader-key
     "e" '(:ignore t :wk "Evaluate")
     "eb" '(eval-buffer :wk "Evaluate elisp in buffer")
     "ed" '(eval-defun :wk "Evaluate defun containing or after point")
     "ee" '(eval-expression :wk "Evaluate an elisp expression")
     "el" '(eval-last-sexp :wk "Evaluate elisp expression before point")
     "er" '(eval-region :wk "Evaluate elisp in region"))
    ;; window
    (emacaroni/leader-key
     "w" '(:ignore t :wk "Window")
     "wn" '(evil-window-next :wk "Wind next")
     "wh" '(evil-window-left :wk "Window left")
     "wl" '(evil-window-right :wk "Window right")
     "wk" '(evil-window-up :wk "Window up")
     "wj" '(evil-window-down :wk "Window down")
     "wH" '(buf-move-left :wk "Buffer move left")
     "wJ" '(buf-move-down :wk "Buffer move down")
     "wK" '(buf-move-up :wk "Buffer move up")
     "wL" '(buf-move-right :wk "Buffer move right"))
    ;; toggles
    (emacaroni/leader-key
     "t" '(:ignore t :wk "Terminal")
     "tf" '(neotree-toggle :wk "Toggle neotree")
     "tl" '(visual-line-mode :wk "Toggle truncated lines")
     "tt" '(vterm-toggle :wk "Toggle vterm")
     "te" '(eshell :wk "Open eshell"))
    
    ;; projectile
    (emacaroni/leader-key
     "p" '(projectile-command-map :wk "Projectile"))
)

#+end_src

* Nerd Icons
#+begin_src emacs-lisp
(use-package nerd-icons
  :ensure t
  :if (display-graphic-p))

(use-package nerd-icons-dired
:ensure t
  :hook (dired-mode . (lambda () (nerd-icons-dired-mode t))))
(use-package nerd-icons-ibuffer
  :ensure t
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

* Auto-Trash Backups
reduce the clutter in directories file.name~ by placing in the trash
#+begin_src emacs-lisp
(setq backup-directory-alits '((".a' ~/.Trash")))
#+end_src

* Diminish
#+begin_src emacs-lisp
(use-package diminish :ensure t)
#+end_src

* Dired
#+begin_src emacs-lisp
(use-package dired-open
  :ensure t
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

(use-package peep-dired
  :ensure t
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "ENTER") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)

;;(add-hook 'peep-dired-hook 'evil-normalize-keymaps)

#+end_src

* Flycheck and Flymake
#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :init (global-flycheck-mode))
(use-package flymake
  :ensure t
  :defer t
  :diminish)
#+end_src

* Fonts
#+begin_src emacs-lisp
(set-face-attribute 'default nil
  :font "JetBrainsMono Nerd Font"
  :height 150 
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "Nebula Sans"
  :height 140
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "JetBrainsMono Nerd Font"
  :height 150
  :weight 'medium)
;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
(add-to-list 'default-frame-alist '(font . "JetBrainsMono Nerd Font-17"))

;; Uncomment the following line if line spacing needs adjusting.
;;(setq-default line-spacing 0.12)
#+end_src

You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.

#+begin_src emacs-lisp
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src


* Important Settings 
** Disable Menubar, toolbars and scrollbars
#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

** Line Numbers and Truncated Lines
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Disable startup screen
#+begin_src emacs-lisp
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(setq initial-major-mode 'org-mode)
#+end_src

** Sensible defaults 
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq indent-line-function 'insert-tab )

(delete-selection-mode 1)
(electric-indent-mode -1)
(electric-pair-mode 1)

;; The following prevents <> from auto-pairing when electric-pair-mode is on.
;; Otherwise, org-tempo is broken when you try to <s TAB...
;; Corrected hook to stop < from auto-closing in Org mode
(add-hook 'org-mode-hook 
          (lambda ()
            (setq-local electric-pair-inhibit-predicate
                        (lambda (c)
                          (if (char-equal c ?<)
                              t ;; Return t means "Do NOT pair this character"
                            (when electric-pair-inhibit-predicate
                              (funcall electric-pair-inhibit-predicate c)))))))

(global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
(global-display-line-numbers-mode 1) ;; Display line numbers
(global-visual-line-mode nil)  ;; Enable truncated lines
(menu-bar-mode -1)           ;; Disable the menu bar 
(scroll-bar-mode -1)         ;; Disable the scroll bar
(tool-bar-mode -1)           ;; Disable the tool bar
(setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
#+end_src


* Ivy (Counsel)
#+begin_src emacs-lisp
(use-package counsel
  :ensure t
  :diminish
  :after ivy
  :config (counsel-mode))

(use-package ivy
  :ensure t
  :diminish
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :config
  (ivy-mode))

(use-package nerd-icons-ivy-rich
  :ensure t
  :init (nerd-icons-ivy-rich-mode 1))
(use-package ivy-rich
  :after ivy
  :ensure t
  :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer))
#+end_src

* Company 
completions...

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :ensure t
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
#+end_src

* Languages 
** LSP
#+begin_src emacs-lisp
(use-package lua-mode :ensure t)
(use-package haskell-mode :ensure t)
(use-package go-mode :ensure t)
(use-package elixir-mode :ensure t)
(use-package rust-mode :ensure t)
(use-package json-mode :ensure t)
(use-package typescript-mode :ensure t)
(use-package lsp-mode :ensure t)
#+end_src

#+begin_src emacs-lisp
(use-package jsonrpc)
(use-package project)
(use-package eglot
     :ensure t
     :hook ((go-mode . eglot-ensure)
            (rust-mode . eglot-ensure)
            (typescript-mode . eglot-ensure)
	    (json-mode . eglot-ensure)
	    (lua-mode . eglot-ensure)))
#+end_src

** Apheleia (FORMATTING)
#+begin_src emacs-lisp
(use-package apheleia
  :ensure t
  :config
  (apheleia-global-mode +1)
  (setf (alist-get 'go-mode apheleia-mode-alist)
        '(goimports gofmt)))  
#+end_src

* Minibuffer escape
#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src

* Modeline
#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 35      ;; sets modeline height
        doom-modeline-bar-width 5    ;; sets right bar width
        doom-modeline-persp-name t   ;; adds perspective name to modeline
        doom-modeline-persp-icon t)) ;; adds folder icon next to persp name
#+end_src

* Org Mode
** Enabling Table of Contents
#+begin_src emacs-lisp
(use-package toc-org
  :ensure t
  :commands toc-org-enable
  :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Enabling Org Bullets
Org-bullets gives us attractive bullets rather than asterisks.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets :ensure t)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Source Code Extension

Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |


#+begin_src emacs-lisp 
(require 'org-tempo)
#+end_src

* Projectile
#+begin_src emacs-lisp
(use-package projectile
  :ensure t
  :config
  (projectile-mode 1))
#+end_src

* Rainbow Mode

#+begin_src emacs-lisp
(use-package rainbow-mode
  :ensure t
  :hook 
  ((org-mode prog-mode) . rainbow-mode))
;; Delimiters
(use-package rainbow-delimiters
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
	 (clojure-mode .rainbow-delimiters-mode)))
#+end_src

* Reload Emacs 
#+begin_src emacs-lisp
(defun reload-init-file ()
  (interactive)
  (load-file user-init-file)
  (load-file user-init-file))
#+end_src

* Shells and Terms
** Eshell
#+begin_src emacs-lisp
(use-package eshell-syntax-highlighting
  :ensure t
  :after esh-mode
  :config
  (eshell-syntax-highlighting-global-mode +1))

;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.
;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
;; eshell-aliases-file -- sets an aliases file for the eshell.
  
(setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
      eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src

** Vterm
#+begin_src emacs-lisp
(use-package vterm
  :ensure t
  :config
(setq shell-file-name "/bin/zsh"
      vterm-max-scrollback 5000))
#+end_src

** Vterm-Toggle
#+begin_src emacs-lisp
(use-package vterm-toggle
  :ensure 
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                     (let ((buffer (get-buffer buffer-or-name)))
                       (with-current-buffer buffer
                         (or (equal major-mode 'vterm-mode)
                             (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                  (display-buffer-reuse-window display-buffer-at-bottom)
                  ;;(display-buffer-reuse-window display-buffer-in-direction)
                  ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                  ;;(direction . bottom)
                  ;;(dedicated . t) ;dedicated is supported in emacs27
                  (reusable-frames . visible)
                  (window-height . 0.60))))
#+end_src

* Sudo Edit
[[https://github.com/nflath/sudo-edit][sudo-edit]] gives us the ability to open files with sudo privileges or switch over to editing with sudo privileges if we initially opened the file without such privileges.

#+begin_src emacs-lisp
(use-package sudo-edit
   :ensure t
   :after general
   :config
     (emacaroni/leader-key
       "fu" '(sudo-edit-find-file :wk "Sudo find file")
       "fU" '(sudo-edit :wk "Sudo edit file"))
)
#+end_src

* Theme
** Themes packages 
#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t
	doom-themes-enable-italic t)
    
(load-theme 'doom-gruvbox t)
)
#+end_src

** Transparency
#+begin_src emacs-lisp
;; Set transparency for the current frame (the one launching)
(set-frame-parameter (selected-frame) 'alpha-background 85)

;; Set transparency for all future frames
(add-to-list 'default-frame-alist '(alpha-background . 85))
#+end_src

* Which-Key
#+begin_src emacs-lisp
(use-package which-key
  :init
    (which-key-mode 1)
  :diminish
  :config
  (setq which-key-side-window-location 'bottom
  which-key-sort-order #'which-key-key-order-alpha which-key-sort-uppercase-first nil
  which-key-add-column-padding 1
  which-key-max-display-columns nil
  which-key-min-display-lines 6
  which-key-side-window-slot -10
  which-key-side-window-max-height 0.25
  which-key-idle-delay 0.2
  which-key-max-description-length 25
  which-key-allow-imprecise-window-fit nil
  which-key-separator " → " ))
#+end_src


