$terminal = ghostty
$fileManager = ghostty -e yazi
$menu = rofi -show drun
$music = spotify
$browser = zen-browser

env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20

general {
    gaps_in = 4 
    gaps_out = 5 

    border_size = 1

    col.active_border = rgba(b4d4cfff)
    col.inactive_border = rgba(1a1b26ff)

    resize_on_border = true

    allow_tearing = false 

    layout = dwindle
}

decoration {
    rounding = 5
    rounding_power = 5

    active_opacity = 1
    inactive_opacity = 0.85
    fullscreen_opacity = 1

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1d2021FF)
    }

    blur {
        enabled = false
        size = 2
        passes = 2
        new_optimizations = on
        popups = true

        vibrancy = 1
    }
}

animations {
    enabled = false,

    bezier = testing, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 5, testing
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1 , 6, default
}

dwindle {
    pseudotile = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 3
}

render {
    direct_scanout = 2
}

cursor {
    no_break_fs_vrr = 2
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1

    sensitivity = .25

    touchpad {
        natural_scroll = true
        scroll_factor = 0.35
        disable_while_typing = false
    }
}

gestures {
   gesture = 3, horizontal, workspace
   gesture = 3, up, mod: SUPER, fullscreen

}

device {
    name = tpps/2-elan-trackpoint
}
