windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = match:class firefox, workspace 2
windowrule = match:class zen, workspace 2
windowrule = match:class brave-bin, workspace 2

windowrule {
    name = pip
    match:title = Picture-in-Picture
    float = yes
    size = 472 270
    move = 1415 834
    pin = yes
    opaque = true
    no_initial_focus = true
    border_size = 0
}

windowrule {
    name = mullvad
    match:class = Mullvad VPN
    workspace = 1
}

windowrule {
    name = ghostty
    match:class = com.mitchellh.ghostty
    workspace = 1
    opacity = .95
}

windowrule {
    name = steam
    match:class = steam
    workspace = 3 silent
}

windowrule {
    name = heroic
    match:class = heroic
    workspace = 3 silent
    float = yes
}

windowrule {
    name = discord
    match:class = discord
    workspace = 3 silent
    float = yes
}

windowrule = match:class org.prismlauncher.PrismLauncher, workspace 3

windowrule = match:class thunar, workspace 4

windowrule {
    name = vpn
    match:class = Mullvad VPN
    workspace = special:magic
    float = yes
    move = 1567 74
}

windowrule {
    name = passwd
    match:class = Bitwarden
    workspace = special:magic
    float = yes
    size = 651, 601
    move = 897, 74
}

windowrule {
    name = spotify
    match:class = spotify
    workspace = special:magic
    float = yes
    size = 859 960
    move = 15 130
}

windowrule {
    name = bluetooth
    match:class = blueman-manager
    workspace = special:magic
    float = yes
    move = 1220 708
    size = 651 452
}

windowrule {
    name = windscribe
    match:class = Windscribe
    float = yes
    pseudo = yes
  }
