set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,tmux-256color:RGB"

set -g mouse on

set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre

# Vague Color Reference:
# bg: #141415 (dark background)
# inactiveBg: #1c1c24 (lighter background)
# line: #252530 (line/highlight)
# comment: #606079 (dim foreground)
# builtin: #b4d4cf (teal/cyan)
# constant: #aeaed1 (purple)
# error: #d8647e (pink/red)
# keyword: #6e94b2 (blue)
# string: #e8b589 (yellow)
# number: #e0a363 (orange)
#
set -g window-status-current-style "fg=#e8b589,bold"
set -g window-status-format "#[fg=#606079]#W"
set -g window-status-current-format "#W"
set -g window-status-separator "#[fg=#606079] | "
set -g status-style "bg=default"
set -g pane-border-style "fg=#252530"
set -g pane-active-border-style "fg=#e8b589"
set -g pane-border-format "#{pane_current_commant}"
set -g mode-style "bg=#e8b589 fg=#141415"
set -g status-left "#[fg=#d8647e,bold]   #S"
set -g status-right ""
# set -g status-right "#[fg=#24A1AD]  #{cpu}  #{mem}"


# Window management
unbind n
bind n new-window -c "#{pane_current_path}"
unbind c
bind c new-session -c "#{pane_current_path}"
bind b break-pane
bind Tab next-window
unbind x
bind x kill-pane
bind l split-window -h -p 50 -c "#{pane_current_path}"
bind J split-window -v -p 40 -c "#{pane_current_path}"
bind j split-window -v -p 20 -c "#{pane_current_path}"



# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Custom scripts
bind G neww -n "lazygit" lazygit
bind E show-environment -g

# TPM path
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins/"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'
set -g @continuum-save-interval '15'

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
